name = "GridapMHD"
uuid = "afadc09e-922c-4d62-8330-7a6898d360cc"
authors = ["Jesús Bonilla", "Francesc Verdugo", "Large Scale Scientific Computing"]
version = "0.3.0"

[deps]
Gridap = "56d4f2e9-7ea1-5844-9cf6-b9c51ca7ce8e"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"

[compat]
Gridap = "0.17"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
